site_name: napari-test2
site_description: A simple plugin to use with napari
site_author: Napari Developer

theme: readthedocs

repo_url: https://github.com/tlambert03/napari-test2

pages:
- Home: index.md
